name: Main

env:
  ORIGIN: ${{ vars.ORIGIN }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PWD: ${{ vars.DB_PWD }}
  TEST: ${{ vars.TEST }}
  TEST_2: ${{ secrets.TEST_2 }}

on:
  workflow_dispatch:
  # Run once a day at 8:00am.
  schedule:
    - cron: '0 0,8 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # example splitting all tests across GitHub machines
  prepare:
    environment: .env
    runs-on: ubuntu-20.04
    steps:    
      - name: Print .env "TEST"
        run: echo "TEST => ${{ vars.TEST }}"
        
      - name: Print .env "TEST_2"
        run: echo "TEST_2 => ${{ secrets.TEST_2 }}"
    
      - name: Print .env "ORIGIN"
        run: echo "ORIGIN => ${{ vars.ORIGIN }}"

      - name: Print .env "DB_HOST"
        run: echo "DB_HOST => ${{ secrets.DB_HOST }}"

      - name: Print .env "DB_PWD"
        run: echo "DB_PWD => ${{ $DB_PWD }}"
        
      
